/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 14:45:27 UTC 
 * Modify at your own risk.
 */

package com.appspot.skillful_octane_742.bankadministrationapi.model;

/**
 * Model definition for Balance.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bankadministrationapi. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Balance extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float balance;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getBalance() {
    return balance;
  }

  /**
   * @param balance balance or {@code null} for none
   */
  public Balance setBalance(java.lang.Float balance) {
    this.balance = balance;
    return this;
  }

  @Override
  public Balance set(String fieldName, Object value) {
    return (Balance) super.set(fieldName, value);
  }

  @Override
  public Balance clone() {
    return (Balance) super.clone();
  }

}
